name: Setup Environment
description: 'Set up Node.js, yarn, Expo CLI'
inputs:
  EXPO_TOKEN:
    required: true
    description: 'Expo API key'

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'yarn'

    - uses: actions/cache@v4
      name: Setup yarn cache
      with:
        path: ~/.yarn/cache
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - uses: expo/expo-github-action@v8
      with:
        eas-version: latest
        token: ${{ inputs.EXPO_TOKEN }}
        packager: yarn

    - name: Install Dependencies
      run: yarn install --frozen-lockfile
      shell: bash
    - name: Install example dependencies
      run: cd example && yarn install --frozen-lockfile
      shell: bash
